energy_data = {
    'Exxon Mobil Corporation': 'XOM',
    'Chevron Corporation': 'CVX',
    'Conoco Phillips': 'COP',
    'SLB': 'SLB',
    'EOG Resources, Inc.': 'EOG',
    'Marathon Petroleum Corporation': 'MPC',
    'Pioneer Natural Resources Company': 'PXD',
    'Phillips 66': 'PSX',
    'Valero Energy Corporation': 'VLO',
    'Occidental Petroleum Corporation': 'OXY',
    'Hess Corporation': 'HES',
    'Williams Cos Inc': 'WMB',
    'Cheniere Energy, Inc.': 'LNG',
    'Baker Hughes Company': 'BKR',
    'Halliburton Company': 'HAL',
    'Kinder Morgan, Inc.': 'KMI',
    'Devon Energy Corporation': 'DVN',
    'ONEOK, Inc.': 'OKE',
    'Diamondback Energy, Inc.': 'FANG',
    'Coterra Energy Inc.': 'CTRA',
    'First Solar, Inc.': 'FSLR',
    'Targa Resources Corp.': 'TRGP',
    'Enphase Energy, Inc.': 'ENPH',
    'Marathon Oil Corporation': 'MRO',
    'EQT Corporation': 'EQT',
    'APA Corporation': 'APA',
    'Ovintiv Inc.': 'OVV',
    'Texas Pacific Land Corporation': 'TPL',
    'Chesapeake Energy Corporation': 'CHK',
    'TechnipFMC plc': 'FTI',
    'NOV Inc.': 'NOV',
    'HF Sinclair Corporation': 'DINO',
    'Antero Resources Corporation': 'AR',
    'Range Resources Corporation': 'RRC',
    'Southwestern Energy Company': 'SWN',
    'USD CASH': 'USD',
    'DT Midstream, Inc.': 'DTM',
    'Plug Power Inc.': 'PLUG',
    'Antero Midstream Corporation': 'AM',
    'ChargePoint Holdings, Inc.': 'CHPT',
    'New Fortress Energy Inc.': 'NFE',
    'BLK CSH FND TREASURY SL AGENCY': 'XTSLA',
    'CASH COLLATERAL USD WFFUT': 'WFFUT',
    'EMINI ENERGY SELECT SECTOR SEP 23': 'IXPU3'
}