finn_data = {
    'Berkshire Hathaway Inc.': 'BRK.B',
    'JPMorgan Chase & Co.': 'JPM',
    'Bank of America Corporation': 'BAC',
    'Wells Fargo & Company': 'WFC',
    'S&P Global Inc.': 'SPGI',
    'The Goldman Sachs Group, Inc.': 'GS',
    'BlackRock, Inc.': 'BLK',
    'Morgan Stanley': 'MS',
    'Marsh & McLennan Companies, Inc.': 'MMC',
    'Charles Schwab Corp.': 'SCHW',
    'Chubb Limited': 'CB',
    'Citigroup Inc.': 'C',
    'The Progressive Corporation': 'PGR',
    'Blackstone Inc.': 'BX',
    'CME Group Inc.': 'CME',
    'Aon plc': 'AON',
    'Intercontinental Exchange, Inc.': 'ICE',
    'U.S. Bancorp': 'USB',
    'MOODYS CORP': 'MCO',
    'Arthur J. Gallagher & Co.': 'AJG',
    'The PNC Financial Services Group, Inc.': 'PNC',
    'Aflac Incorporated': 'AFL',
    'Apollo Global Management, Inc.': 'APO',
    'American International Group, Inc.': 'AIG',
    'MSCI Inc.': 'MSCI',
    'MetLife, Inc.': 'MET',
    'Truist Financial Corporation': 'TFC',
    'KKR & Co. Inc.': 'KKR',
    'Travelers Companies Inc.': 'TRV',
    'Ameriprise Financial, Inc.': 'AMP',
    'The Bank of New York Mellon Corporation': 'BK',
    'Prudential Financial, Inc.': 'PRU',
    'The Allstate Corporation': 'ALL',
    'Arch Capital Group Ltd.': 'ACGL',
    'T. Rowe Price Group, Inc.': 'TROW',
    'State Street Corporation': 'STT',
    'Discover Financial Services': 'DFS',
    'Willis Towers Watson PLC': 'WTW',
    'Hartford Financial Services Group Inc.': 'HIG',
    'Broadridge Financial Solutions, Inc.': 'BR',
    'M&T Bank Corporation': 'MTB',
    'Raymond James Financial, Inc.': 'RJF',
    'Markel Corporation': 'MKL',
    'Principal Financial Group, Inc.': 'PFG',
    'LPL Financial Holdings Inc.': 'LPLA',
    'Nasdaq, Inc.': 'NDAQ',
    'Fifth Third Bancorp': 'FITB',
    'Brown & Brown, Inc.': 'BRO',
    'Regions Financial Corporation': 'RF',
    'FactSet Research Systems Inc.': 'FDS'
}